version: '3.1'

services: 
  db:
    build: ./database
    environment:
      POSTGRES_PASSWORD: "pgadmin#2345@"
    ports:
      - "5432:5432"
    volumes:
      - C:/Users/roger/DEV/Docker/Postgres/data:/var/lib/postgresql/data  
    networks:
      - biblio-network
  api:
    depends_on:
      - db
    links: 
      - db
    build: ./spring-boot-rest-api
    working_dir: /spring-boot-rest-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./spring-boot-rest-api:/spring-boot-rest-api
      - .m2:/root/.m2
    environment: 
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIROMENT: Production
    command: mvn clean spring-boot:run  
    networks:
      - biblio-network  
networks: 
  biblio-network:
    driver: bridge